[include]
files = [
  "modules/binds.toml",
  "modules/inputs.toml",
  "modules/startup.toml",
  "modules/workspaces.toml",
  "modules/animations.toml",
  "modules/rules.toml",
  "modules/overview.toml",
  "modules/layouts.toml",
  "modules/appearance.toml"
]                                      # Example: ["appearance.toml", "outputs.toml"]

[include.optional]
files = []                                      # Example: ["~/.config/umbriel/noctalia.toml"]

[general]
xwayland = true                                 # Requires xwayland-satellite; restart to change
show_cheatsheet = false                          # Show the keybind overlay on startup
focus_on_activate = false                       # Do not let unsolicited requests steal focus
honor_restored_maximize = false                 # Honor restored maximized state

#
