## This is where your keyboard and mouse settings will exist
# Can't find what you're looking for? Try ./binds.conf
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = altwin:menu_win, caps:escape
    kb_rules =

    # Mouse Settings
    follow_mouse = 1 
    sensitivity = -1
    force_no_accel = 0
}
