## This is for your windows and workspaces# Example windowrules that are useful
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = dont-animate-flameshot
    match:class = flameshot
    no_anim = on
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = floating-kitty
    match:class = kitty
    float = 1
    min_size = 1920, 1080
}

# Workspace 1 is floating windows
windowrule {
	name = floating-workspace
    match:workspace = 1
    float = 1 
}

# Discord opens on workspace 3
windowrule {
	name = wkspc3-discord
	match:class = discord
	workspace = 3
}

#workspace 4 is for steam specifically

windowrule {
    name = steam-floats-wkspc4
    match:initial_class = steam
    workspace = 4
    float = 1
}
windowrule {
    name = wkspc5-games
    match:class = org.vinegarhq.Sober
    workspace = 5
}

windowrule {
    name = wkspc5-games-steam
    match:class = gamescope
    workspace = 5
    fullscreen = yes
}

# Fullscreen Applications open on workspace 5

windowrule {
	name = fullscr-on-5
	match:fullscreen = yes
	workspace = 5
}

# Hyprland-run windowrule
windowrule {
    name = window

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# named rule syntax (Hyprland 0.53+)
# blur
layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

# disable animation for vicinae only
layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}

