volume-max=150
volume-gain=5
autofit=33%
ao=pulse
--use-filedir-conf
# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no
