## This is basically your STARTUP folder
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# music
exec-once = rmpc

# uac/privilege escalation
exec-once = systemctl --user start hyprpolkitagent

# info bar
exec-once = qs

# notification center
exec-once = swaync

# auto-replay-buffer start
exec-once = obs --minimize-to-tray --disable-shutdown-check


# wallpaper
exec-once = awww-daemon

# clipboard manager (cliphist)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
