source = ~/.config/hypr/modules/monitor.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/general.conf
source = ~/.config/hypr/modules/animation.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/gestures.conf
source = ~/.config/hypr/modules/layouts.conf
source = ~/.config/hypr/modules/lookandfeel.conf
source = ~/.config/hypr/modules/misc.conf
source = ~/.config/hypr/modules/windowrules.conf
